FROM ollama/ollama:0.5.7

# Start ollama and pull the models during the build process
RUN (ollama serve &) && sleep 10 && \
    ollama pull llama3.3 && \
    ollama pull phi3:mini && \
    ollama pull nomic-embed-text && \
    pkill ollama

EXPOSE 11434
